<a href="https://colab.research.google.com/github/enidroman/Data_602_Advanced_Programming_and_Techniques/blob/main/QOTW_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. What are the similarities and differences between pandas and numpy?   Include some type of example with code.

A pandas Series is very similar to a one-dimensional NumPy array. Python is built on top of the NumPy package, which means Numpy is required for operating the Pandas. Both Pandas and NumPy simplify matrix multiplication and therefore are being heavily used in the field of Data Science, especially model developments in Machine Learning. 

The difference is Pandas is mostly used for data analysis tasks in Python. NumPy is mostly used for working with Numerical values as it makes it easy to apply mathematical functions. Pandas library works well for numeric, alphabets, and heterogeneous types of data simultaneously. Numpy library works better with only numerical data, has efficient storage, and fastly performs mathematical operations on array-based and array-based matrix-based numeric values. If the number of rows of the dataset is more than five hundred thousand (500K), then the performance of Pandas is better than NumPy. NumPy can be said to be faster in performance than Pandas, up to fifty thousand (50K) rows and less of the dataset.  (The performance between fifty thousand rows to five hundred thousand rows mostly depends on the type of operation Pandas, and NumPy are going to have to perform.) DataFrames and Series are the most powerful tools for Pandas. Arrays are the most powerful tool of NumPy. Pandas consume more memory compared to NumPy. NumPy has lesser memory consumption compared to Pandas. DataFrames are the two-dimensional (2d) Objects provided by Pandas. NumPy provides n-dimensional arrays, Data Type (dtype), etc. as objects. The indexing of pandas series is significantly slower than the indexing of NumPy arrays. The indexing of NumPy arrays is much faster than the indexing of Pandas arrays. Pandas have a higher industry application compared to NumPy as mentioned in 73 company stacks and 46 developer stacks. NumPy has a lower industry application compared to Pandas as mentioned in 62 company stacks and 32 developer stacks.

In [ ]:
# Example of pandas code:

# Importing pandas library
import pandas as pd
 
# Creating and initializing a nested list
age = [['Aman', 95.5, "Male"], ['Sunny', 65.7, "Female"],
       ['Monty', 85.1, "Male"], ['toni', 75.4, "Male"]]
 
# Creating a pandas dataframe
df = pd.DataFrame(age, columns=['Name', 'Marks', 'Gender'])
 
# Printing dataframe
df

Name  Marks  Gender
0   Aman   95.5    Male
1  Sunny   65.7  Female
2  Monty   85.1    Male
3   toni   75.4    Male

In [ ]:
# Example of numpy code: 

# Importing Numpy package
import numpy as np
 
# Creating a 3-D numpy array using np.array()
org_array = np.array([[23, 46, 85],
                      [43, 56, 99],
                      [11, 34, 55]])
 
# Printing the Numpy array
print(org_array)

[[23 46 85]
 [43 56 99]
 [11 34 55]]


2. What is the ndarray in numPy?

The main data structure in NumPy is the ndarray, which is a shorthand name for N-dimensional array. When working with NumPy, data in an ndarray is simply referred to as an array. It is a fixed-sized array in memory that contains data of the same type, such as integers or floating point values. The data type supported by an array can be accessed via the “dtype” attribute on the array. The dimensions of an array can be accessed via the “shape” attribute that returns a tuple describing the length of each dimension. 

3. Create a 1D array of numbers from 0 to 9 

Desired Output: 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create array
import numpy as np
np.__version__
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4. Extract all odd numbers from array1 

array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

5. Get the common items between a and b  

#input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Desired Output:

array([2, 4])

In [ ]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a, b)

array([2, 4])

6. From array a remove all items present in array b 

#Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

#Desired Output:

array([1,2,3,4])

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

7. Find out if iris has any missing values. 



# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

print("Number of missing values: \n", np.isnan(iris[:,0]).sum())

Number of missing values: 
 0
